##############################################################################
### IMPORTANT: ALL FIELDS MUST BE COMPLETED OTHERWISE AN ERROR WILL OCCUR! ###
##############################################################################


####################
### Bot Settings ###
####################
BotSettings:
  bot_token: some-token
  test_mode_enabled: false
  number_of_shards: 1
  evelyn_shard_number: 0
  support_server_id: 355811657760505868
  ghost_mode_enabled: false
  message_filtering_server_size: 150
  typing_enabled: false
  voice_commands_enabled: false
  contributor_sign_role: -1
  supporter_sign_role: -1


######################
### Update Scripts ###
######################
  #IMPORTANT: These must be located at the root directory of the project.
  #NOTE: If you are on linux, use sh files and chmod +x them. For windows use a .bat file ending.
UpdateScripts:
  pull_script: Pull.sh
  build_script: Build.sh
  update_script: Update.sh


#########################
### Database Settings ###
#########################
DatabaseSettings:
  ip_address: randomip
  port: 3306
  username: username
  password: password
  db_name: name


#############################
### 3rd Party Auth Tokens ###
#############################
AuthKeys:
  bitly_token: na
  cat_api_token: na
  giphy_token: na
  google_api_token: na
  riot_games_token: na
  twitch_id: na
  twitter_key: na
  twitter_secret: na


######################
### Audio Settings ###
######################
AudioSettings:
  audio_file_types: opus, mp3
  audio_format: mp3
  music_download_threads: 1
  track_expiration_time: 432000000
  required_plays_to_download: 100


#######################
### Folder Settings ###
#######################
  #IMPORTANT: These folders must already exist. It will not auto-create them. (yet)
  #IMPORTANT: Make sure there is a / at the end of your path.
  #NOTE: Use the / seperator for Windows as well as for Unix. For Windows include the drive like C:/some/path/
FolderSettings:
  audio_folder: C:/Users/someuser/IdeaProjects/DiscordBot/Audio/
  badge_folder: C:/Users/someuser/IdeaProjects/DiscordBot/Badges/
  logs_folder: C:/Users/someuser/IdeaProjects/DiscordBot/Logs/
  neural_net_folder: C:/Users/someuser/IdeaProjects/DiscordBot/Neural_net/
  temp_folder: C:/Users/someuser/IdeaProjects/DiscordBot/Temp/


######################
### Resource Files ###
######################
  #IMPORTANT: Make sure to include the full path to the file as well as the file ending.
ResourceFiles:
  emoticons: C:/Users/someuser/IdeaProjects/DiscordBot/Resources/Emoticons.txt
  fake_danger: C:/Users/someuser/IdeaProjects/DiscordBot/Resources/FakeDanger.txt
  final_map: C:/Users/someuser/IdeaProjects/DiscordBot/Resources/FinalMap.png
  guide: C:/Users/someuser/IdeaProjects/DiscordBot/Resources/Guide.txt
  language_filtering: C:/Users/someuser/IdeaProjects/DiscordBot/Resources/LanguageFiltering.txt
  supported_langs: C:/Users/someuser/IdeaProjects/DiscordBot/Resources/SupportedLangs.txt
  time_stats: C:/Users/someuser/IdeaProjects/DiscordBot/Resources/TimeStats.txt
  verified_games: C:/Users/someuser/IdeaProjects/DiscordBot/Resources/VerifiedGames.txt


#################
### Libraries ###
#################
  #IMPORTANT: Ensure to include the full path to the executable.
  #NOTE: Linux users can install youtube-dl using these instructions: https://rg3.github.io/youtube-dl/download.html
LibrariesFiles:
  ffm_peg: C:/Users/someuser/IdeaProjects/DiscordBot/Libraries/ffmpeg.exe
  youtube_dl: C:/Users/someuser/IdeaProjects/DiscordBot/Libraries/youtube-dl.exe