##############################################################################
### IMPORTANT: ALL FIELDS MUST BE COMPLETED OTHERWISE AN ERROR WILL OCCUR! ###
##############################################################################


####################
### Bot Settings ###
####################
BotSettings:
  botToken: MzU2NTU4MDE2NjI1MjQ2MjIx.DOH1fA.mcPYIx5DebhMxcgKJS-5Ji_R2Qk
  testModeEnabled: false
  numberOfShards: 1
  evelynShardNumber: 0
  supportServerId: 355811657760505868
  ghostModeEnabled: false
  messageFilteringServerSize: 150
  typingEnabled: false
  voiceCommandsEnabled: false
  contributorSignRole: -1
  supporterSignRole: -1
  loggingChannel: 398634800384311300


######################
### Update Scripts ###
######################
  #IMPORTANT: These must be located at the root directory of the project.
  #NOTE: If you are on linux, use sh files and chmod +x them. For windows use a .bat file ending.
UpdateScripts:
  pullScript: Pull.sh
  buildScript: Build.sh
  updateScript: Update.sh


#########################
### Database Settings ###
#########################
DatabaseSettings:
  ipAddress: localhost
  port: 3306
  username: Evelyn
  password: hitlerdidnothingwrong
  dbName: Evelyn


#############################
### 3rd Party Auth Tokens ###
#############################
AuthKeys:
  bitlyToken: d45d3e6064e9607235a045f7b4e56ec1a463dce2
  catApiToken: na
  giphyToken: na
  googleApiToken: na
  riotGamesToken: na
  twitchId: na
  twitterKey: na
  twitterSecret: na


######################
### Audio Settings ###
######################
AudioSettings:
  audioFileTypes: opus, mp3
  audioFormat: mp3
  musicDownloadThreads: 1
  trackExpirationTime: 432000000
  requiredPlaysToDownload: 100
  

#######################
### Folder Settings ###
#######################
  #IMPORTANT: These folders must already exist. It will not auto-create them. (yet)
  #IMPORTANT: Make sure there is a / at the end of your path.
  #NOTE: Use the / seperator for Windows as well as for Unix. For Windows include the drive like C:/some/path/
FolderSettings:
  audioFolder: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/audio/
  badgeFolder: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/badges/
  logsFolder: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/logs/
  neuralNetFolder: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/neuralnet/
  tempFolder: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/temp/


######################
### Resource Files ###
######################
  #IMPORTANT: Make sure to include the full path to the file as well as the file ending.
ResourceFiles:
  emoticons: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/required/Emoticons.txt
  fakeDanger: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/required/FakeDanger.txt
  finalMap: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/required/FinalMap.png
  guide: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/required/Guide.txt
  languageFiltering: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/required/LanguageFiltering.txt
  supportedLangs: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/required/SupportedLangs.txt
  timeStats: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/required/TimeStats.txt
  verifiedGames: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/required/VerifiedGames.txt


#################
### Libraries ###
#################
  #IMPORTANT: Ensure to include the full path to the executable.
  #NOTE: Linux users can install youtube-dl using these instructions: https://rg3.github.io/youtube-dl/download.html
LibrariesFiles:
  ffmPeg: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/libraries/ffmpeg.exe
  youtubeDl: /Users/mathiasbjelke/Desktop/Repositories/Evelyn/libraries/youtube-dl.exe