URLs:
  bot_invite_url: https://discordapp.com/oauth2/authorize?client_id=355764285387046924&scope=bot&permissions=70634560
  discord_invite_url: https://discord.gg/UW5X5BU
  rickroll_vid: https://youtu.be/dQw4w9WgXcQ
  bank_gif: https://media.giphy.com/media/iQxHV4HVDJuk8/giphy.gif
  currencytree_gif: https://media.giphy.com/media/ZPFQVis9WAAcE/giphy.gif
  announce_thumb: https://cdn.discordapp.com/attachments/374538747229896704/384862519354982403/38153-200.png
  patreon_url: https://www.patreon.com/soarnija

